version: "3.8"

services:

  nginx:
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
    container_name: ${APP_NAME}-web
    volumes:
      - ./:/var/www/html/
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/nginx/sites/:/etc/nginx/sites-available
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php
    ports:
      - 8000:80
      - 443:443
    networks:
      - bubbles

  php:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    container_name: ${APP_NAME}-php
    volumes:
      - ./:/var/www/html/
      - ./.docker/php/conf.d/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - mysql
    environment:
      NETTE_DEBUG: 1
    networks:
      - bubbles

  mysql:
    image: library/mysql:latest
    container_name: ${APP_NAME}-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - bubbles

  adminer:
    image: dockette/adminer:dg
    container_name: ${APP_NAME}-adminer
    ports:
      - 8080:80
    networks:
      - bubbles

volumes:
  mysql-data:

networks:
  bubbles:
    driver: bridge